### ISSUE TITLE
Odd reads

### ISSUE THREAD

**Issue by lynxthecat** [lynxthecat/cake-autorate#178] opened 2023-03-12 00:01 UTC
@rany2, @patrakov and @moeller0 I am still working on the tsping wrapper and am super confused by this read inside the tsping monitor:

https://github.com/lynxthecat/cake-autorate/blob/bc6d02c8058205fe75b6c31786a5bee08036ec46/cake-autorate.sh#L522

with this debug echo:

https://github.com/lynxthecat/cake-autorate/blob/bc6d02c8058205fe75b6c31786a5bee08036ec46/cake-autorate.sh#L525

Giving the following line:

```
START timestamp=DEBUG; reflector=2023-03-11-23:52:59; seq=1678578779.603675; dl_owd_ms= ul_owd_ms= END
```

The pinger_fd is created here:

https://github.com/lynxthecat/cake-autorate/blob/bc6d02c8058205fe75b6c31786a5bee08036ec46/cake-autorate.sh#L776

The log_fd is created here

https://github.com/lynxthecat/cake-autorate/blob/bc6d02c8058205fe75b6c31786a5bee08036ec46/cake-autorate.sh#L1479

My original guess was that the pinger_fd was somehow getting set to the log_fd, but I do not think this is the case:

```
START timestamp=DEBUG; reflector=2023-03-12-08:09:44; seq=1678608584.919980; dl_owd_ms= ul_owd_ms= END
continuing
START timestamp=DEBUG; reflector=2023-03-12-08:09:44; seq=1678608584.921895; dl_owd_ms=to: ul_owd_ms=PAUSED END
DEBUG; 2023-03-12-08:09:45; 1678608585.024608; Starting: kill_monitor_reflector_responses_tsping with PID: 17237
log_fd = 12 pinger_fd = 13
```

And it is just the first few lines of a bad fork of monitor_reflector_responses_tsping():

```
DEBUG; 2023-03-12-08:46:03; 1678610763.295552; Starting: start_pinger with PID: 4152
pinger_fd = 13
DEBUG; 2023-03-12-08:46:03; 1678610763.304218; Warning: no reflector response within: 0.250000 seconds. Checking for loads.
DEBUG; 2023-03-12-08:46:03; 1678610763.310112; load check is: ((5 kbps > 10 kbps && 2 kbps > 10 kbps))
DEBUG; 2023-03-12-08:46:03; 1678610763.312600; Warning: connection stall detection. Waiting for new ping or increased load
DEBUG; 2023-03-12-08:46:03; 1678610763.360450; Starting: monitor_reflector_responses_tsping with PID: 4405
94.140.15.15 = 31690
94.140.15.16 = 100000
208.67.220.220 = 100000
208.67.220.123 = 100000
185.228.169.11 = 40000
208.67.220.2 = 100000
64.6.64.6 = 100000
64.6.65.6 = 100000
185.228.168.10 = 100000
94.140.14.141 = 100000
94.140.14.140 = 100000
185.228.168.9 = 29001
185.228.168.168 = 100000
94.140.14.15 = 100000
208.67.222.123 = 100000
208.67.222.222 = 100000
185.228.169.9 = 100000
156.154.70.1 = 100000
156.154.70.2 = 100000
156.154.70.3 = 100000
156.154.70.4 = 100000
156.154.70.5 = 100000
149.112.112.10 = 100000
149.112.112.11 = 100000
9.9.9.11 = 100000
9.9.9.10 = 28001
185.228.169.168 = 39791
156.154.71.5 = 100000
156.154.71.4 = 100000
156.154.71.1 = 100000
156.154.71.3 = 100000
156.154.71.2 = 100000
208.67.222.2 = 100000
149.112.112.112 = 100000
START timestamp=DEBUG; reflector=2023-03-12-08:46:03; seq=1678610763.328786; dl_owd_ms= ul_owd_ms= END










**** SKIPPING ul_owd_ms=unset ****
START timestamp=DEBUG; reflector=2023-03-12-08:46:03; seq=1678610763.330641; dl_owd_ms=to: ul_owd_ms=PAUSED END










**** SKIPPING ul_owd_ms=PAUSED ****
START timestamp=1678610763.420937 reflector=94.140.15.15 seq=0 dl_owd_ms=30 ul_owd_ms=13 END
LOAD; 2023-03-12-08:46:03; 1678610763.449346; 1678610763.449002; 2; 6; 20000; 16362
START timestamp=1678610763.507013 reflector=185.228.169.168 seq=0 dl_owd_ms=41 ul_owd_ms=140 END
START timestamp=1678610763.520945 reflector=94.140.14.15 seq=0 dl_owd_ms=31 ul_owd_ms=12 END
START timestamp=1678610763.579828 reflector=9.9.9.10 seq=0 dl_owd_ms=28 ul_owd_ms=23 END
START timestamp=1678610763.606953 reflector=185.228.169.11 seq=0 dl_owd_ms=40 ul_owd_ms=139 END
START timestamp=1678610763.632886 reflector=185.228.168.9 seq=0 dl_owd_ms=30 ul_owd_ms=24 END
```

Full output from cake-autorate below with the various debugging lines I've added.

Console output:

https://pastebin.com/raw/1Dej4gZr

Log file output:

https://pastebin.com/raw/VvSJAski

Notice that this line from the read:

```
START timestamp=DEBUG; reflector=2023-03-12-08:46:03; seq=1678610763.330641; dl_owd_ms=to: ul_owd_ms=PAUSED END
````

relates to this line in the log file:

```
"DEBUG; 2023-03-12-08:46:03; 1678610763.330641; Changing maintain_pingers state from: RUNNING to: PAUSED"
```

but there was no corresponding line in the console output. So for whatever reason this printf:

https://github.com/lynxthecat/cake-autorate/blob/bc6d02c8058205fe75b6c31786a5bee08036ec46/cake-autorate.sh#L110

ended up getting read in by the read of pinger_fds[pinger].

The particular log_msg call that ended up getting inside pinger_fds[pinger] is here:

https://github.com/lynxthecat/cake-autorate/blob/bc6d02c8058205fe75b6c31786a5bee08036ec46/cake-autorate.sh#L960

It is far too much of a coincidence that this is inside a trap handler.

**Comment by lynxthecat** [comment] 2023-03-12 08:12
Update: not sure that's the issue since the log_fd and pinger_fd are apparently different:

```
START timestamp=DEBUG; reflector=2023-03-12-08:09:44; seq=1678608584.919980; dl_owd_ms= ul_owd_ms= END
continuing
START timestamp=DEBUG; reflector=2023-03-12-08:09:44; seq=1678608584.921895; dl_owd_ms=to: ul_owd_ms=PAUSED END
DEBUG; 2023-03-12-08:09:45; 1678608585.024608; Starting: kill_monitor_reflector_responses_tsping with PID: 17237
log_fd = 12 pinger_fd = 13
```

**Comment by lynxthecat** [comment] 2023-03-12 08:48
Further update - it is just the first couple of lines on a bad fork of monitor_reflector_responses_tsping():

```
DEBUG; 2023-03-12-08:46:03; 1678610763.295552; Starting: start_pinger with PID: 4152
pinger_fd = 13
DEBUG; 2023-03-12-08:46:03; 1678610763.304218; Warning: no reflector response within: 0.250000 seconds. Checking for loads.
DEBUG; 2023-03-12-08:46:03; 1678610763.310112; load check is: ((5 kbps > 10 kbps && 2 kbps > 10 kbps))
DEBUG; 2023-03-12-08:46:03; 1678610763.312600; Warning: connection stall detection. Waiting for new ping or increased load
DEBUG; 2023-03-12-08:46:03; 1678610763.360450; Starting: monitor_reflector_responses_tsping with PID: 4405
94.140.15.15 = 31690
94.140.15.16 = 100000
208.67.220.220 = 100000
208.67.220.123 = 100000
185.228.169.11 = 40000
208.67.220.2 = 100000
64.6.64.6 = 100000
64.6.65.6 = 100000
185.228.168.10 = 100000
94.140.14.141 = 100000
94.140.14.140 = 100000
185.228.168.9 = 29001
185.228.168.168 = 100000
94.140.14.15 = 100000
208.67.222.123 = 100000
208.67.222.222 = 100000
185.228.169.9 = 100000
156.154.70.1 = 100000
156.154.70.2 = 100000
156.154.70.3 = 100000
156.154.70.4 = 100000
156.154.70.5 = 100000
149.112.112.10 = 100000
149.112.112.11 = 100000
9.9.9.11 = 100000
9.9.9.10 = 28001
185.228.169.168 = 39791
156.154.71.5 = 100000
156.154.71.4 = 100000
156.154.71.1 = 100000
156.154.71.3 = 100000
156.154.71.2 = 100000
208.67.222.2 = 100000
149.112.112.112 = 100000
START timestamp=DEBUG; reflector=2023-03-12-08:46:03; seq=1678610763.328786; dl_owd_ms= ul_owd_ms= END










**** SKIPPING ul_owd_ms=unset ****
START timestamp=DEBUG; reflector=2023-03-12-08:46:03; seq=1678610763.330641; dl_owd_ms=to: ul_owd_ms=PAUSED END










**** SKIPPING ul_owd_ms=PAUSED ****
START timestamp=1678610763.420937 reflector=94.140.15.15 seq=0 dl_owd_ms=30 ul_owd_ms=13 END
LOAD; 2023-03-12-08:46:03; 1678610763.449346; 1678610763.449002; 2; 6; 20000; 16362
START timestamp=1678610763.507013 reflector=185.228.169.168 seq=0 dl_owd_ms=41 ul_owd_ms=140 END
START timestamp=1678610763.520945 reflector=94.140.14.15 seq=0 dl_owd_ms=31 ul_owd_ms=12 END
START timestamp=1678610763.579828 reflector=9.9.9.10 seq=0 dl_owd_ms=28 ul_owd_ms=23 END
START timestamp=1678610763.606953 reflector=185.228.169.11 seq=0 dl_owd_ms=40 ul_owd_ms=139 END
START timestamp=1678610763.632886 reflector=185.228.168.9 seq=0 dl_owd_ms=30 ul_owd_ms=24 END
```

**Comment by moeller0** [comment] 2023-03-12 10:05
Maybe switching back to use filenames instead of file descriptors would avoid this problem?

Also moving the actual pinger start and fifo creation into the monitor process might be a good idea, no?

**Comment by lynxthecat** [comment] 2023-03-12 10:24
Could the issue be related to this:

https://github.com/lynxthecat/cake-autorate/blob/bc6d02c8058205fe75b6c31786a5bee08036ec46/cake-autorate.sh#L853

I think that should be:

```
exec "${pinger_fds[pinger]}"<&-
```

Actually how do you ensure that that doesn't error out if the fd is already closed?

**Comment by moeller0** [comment] 2023-03-12 11:07
Maybe exec does not like the quotes around the file descriptor?
Have you tried:
```
[[ -e /proc/self/fd/"${pinger_fds[pinger]}" ]] && exec ${pinger_fds[pinger]}<&-
```

**Comment by moeller0** [comment] 2023-03-12 11:08
But honestly, why inherit a file descriptor here in the first place, the calling process does not need to access that FIFO (which IIRC only serves between pinger binary and pinger monitor process)?

**Comment by lynxthecat** [comment] 2023-03-12 11:10
This could be a red herring. It seems the printf to stdout originating from this call:

https://github.com/lynxthecat/cake-autorate/blob/bc6d02c8058205fe75b6c31786a5bee08036ec46/cake-autorate.sh#L960

within trap context is always respondible for the read -u pinger_fds[pinger] getting read as:

```
 timestamp=DEBUG; reflector=2023-03-12-11:06:11; seq=1678619171.321864; dl_owd_ms=to: ul_owd_ms=PAUSED
```

**Comment by moeller0** [comment] 2023-03-12 11:17
Well, I have been too subtle so far, but this is IMHO not how state changes should be handled, keep the trap functions to the absolute minimum, only toggle a variable or increment a counter and then have the normal state progression deal with that request for change. 
Really, concurrency is hard, so try to avoid it as much as possible, and here the maintain_pingers() state machine can be run with minimal trapping required and naturally handle the required serialization.
A trap function can easily disturb control flow so let's try to avoid falling into that "trap". Here "boring" control flow is a virtue, and "bleeding edge" not where a robust and reliable controller wants to find itself at ;)

**Comment by moeller0** [comment] 2023-03-12 11:49
But with or without extended trappings, I bet switching back to file names for the FIFOs instead of file descriptors should plug that race we see as well.
That change "filenames to FDs" was motivated by preference and cleaner looking code (not by a functional improvement IIRC) and potential side effects of doing that were not expected/explored, maybe it is time to undo that change now that some side-effects have become clearer?

**Comment by rany2** [comment] 2023-03-12 12:16
@moeller0 For the most part I don't think it is related to the filenames to FD change. My bet is that you're starting tsping wrong. If you don't redirect stderr, you will notice it is erroring out with:

```
Warning: We've sent 135400 packets, but received none.
Something went wrong while sending to 1.1.1.1: No buffer space available
Warning: We've sent 135400 packets, but received none.
Something went wrong while sending to 1.1.1.1: No buffer space available
Something went wrong while sending to 1.1.1.1: No buffer space available
Something went wrong while sending to 1.1.1.1: No buffer space available
Something went wrong while sending to 1.1.1.1: No buffer space available
Something went wrong while sending to 1.1.1.1: No buffer space available
Something went wrong while sending to 1.1.1.1: No buffer space available
Something went wrong while sending to 1.1.1.1: No buffer space available
Something went wrong while sending to 1.1.1.1: No buffer space available
Something went wrong while sending to 1.1.1.1: No buffer space available
Something went wrong while sending to 1.1.1.1: No buffer space available
Something went wrong while sending to 1.1.1.1: No buffer space available
Something went wrong while sending to 1.1.1.1: No buffer space available
Something went wrong while sending to 1.1.1.1: No buffer space available
Something went wrong while sending to 1.1.1.1: No buffer space available
Something went wrong while sending to 1.1.1.1: No buffer space available
Something went wrong while sending to 1.1.1.1: No buffer space available
Something went wrong while sending to 1.1.1.1: No buffer space available
Something went wrong while sending to 1.1.1.1: No buffer space available
Something went wrong while sending to 1.1.1.1: No buffer space available
Something went wrong while sending to 1.1.1.1: No buffer space available
Something went wrong while sending to 1.1.1.1: No buffer space available
Something went wrong while sending to 1.1.1.1: No buffer space available
Something went wrong while sending to 1.1.1.1: No buffer space available
Something went wrong while sending to 1.1.1.1: No buffer space available
Something went wrong while sending to 1.1.1.1: No buffer space available
Something went wrong while sending to 1.1.1.1: No buffer space available
Something went wrong while sending to 1.1.1.1: No buffer space available
Something went wrong while sending to 1.1.1.1: No buffer space available
Something went wrong while sending to 1.1.1.1: No buffer space available
Something went wrong while sending to 1.1.1.1: No buffer space available
Something went wrong while sending to 1.1.1.1: No buffer space available
Something went wrong while sending to 1.1.1.1: No buffer space available
Something went wrong while sending to 1.1.1.1: No buffer space available
Something went wrong while sending to 1.1.1.1: No buffer space available
Something went wrong while sending to 1.1.1.1: No buffer space available
Something went wrong while sending to 1.1.1.1: No buffer space available
```

**Comment by rany2** [comment] 2023-03-12 12:19
@lynxthecat I found the source so to speak (at least in my case), remove the `--sleep-time` parameter and add `-e` to use ICMP echo instead of timestamp requests (timestamp doesn't work for any of my reflectors).

**Comment by moeller0** [comment] 2023-03-12 12:26
> @moeller0 For the most part I don't think it is related to the filenames to FD change.

I wish I had your optimism.... if we write stuff to an FD to a FIFO and read stuff from FIFO A that was written to FIFO B in a short time window after process start/fork, this smells pretty much like a race condition in adjusting the FD numbers between parent and child process. Something that could not exist when using filenames... so I very much see this as a consequence of a change that lacked any real justification in the first place. Changing apparently correctly working code  always introduces the chance to introduce bugs.

> My bet is that you're starting tsping wrong.

I am not starting tsping at all yet in my toy version... so while I am responsible for my own share of bugs and certainly tasteless code, this is not one of them ;)



> If you don't redirect stderr, you will notice it is erroring out with:

Interesting, good catch. But that does not explain how a log_msg write was read by a read of `-u "${pinger_fds[pinger]}"`. The result from a failing tsping invocation should be an empty {pinger_fds[pinger]} instead.

**Comment by rany2** [comment] 2023-03-12 12:35
> this smells pretty much like a race condition in adjusting the FD numbers between parent and child process. Something that could not exist when using filenames... so I very much see this as a consequence of a change that lacked any real justification in the first place

Well, I just realized something else. The read is wrong, the tsping output is:

`1678624419.439710 8.8.8.8 1 41` so read should be something like `read timestamp reflector seq seq_rtt`

**Comment by moeller0** [comment] 2023-03-12 12:36
No this is because you use `-e` which causes a different output in tsping... you are not testing the same as @lynxthecat here.

**Comment by moeller0** [comment] 2023-03-12 12:40
See the different output definitions for tsping:
line 174ff:
 https://github.com/Lochnair/tsping/blob/main/main.c
```
	char FMT_ICMP_ECHO_HUMAN[] = "%-15s : [%u], %d ms\n";
	char FMT_ICMP_ECHO_MACHINE[] = "%s,%u,%d\n";
	char FMT_ICMP_TIMESTAMP_HUMAN[] = "%-15s : [%u] Originate: %u, Received: %u, Transmit: %u, Finished: %u, RTT: %d, Down: %d, Up: %d,\n";
	char FMT_ICMP_TIMESTAMP_MACHINE[] = "%s,%u,%u,%u,%u,%u,%d,%d,%d\n";
	char FMT_TIMESTAMPS_HUMAN[] = "[%lu.%06lu] ";
	char FMT_TIMESTAMPS_MACHINE[] = "%lu.%06lu,";
```

**Comment by rany2** [comment] 2023-03-12 12:41
@moeller0 Ah, if only it was that simple... could confirm, though if tsping were to be used, it's a good idea to drop some reflectors which filter ICMP timestamp requests. So far only 9.9.9.9 works OK.

**Comment by rany2** [comment] 2023-03-12 12:44
I'm having tsping hang, does anyone have this issue as well? Perhaps it's a tsping bug...

```
garbageServer# sudo ./tsping --print-timestamps --machine-readable=' ' --target-spacing "100000" --sleep-time=0 9.9.9.9 9.9.9.10 208.67.220.220 208.67.220.123 185.228.169.11 208.67.220.2 64.6.64.6 64.6.65.6 2>/dev/null
1678625055.148980 9.9.9.9 0 45855141 45855065 45855065 45855148 7 83 -76
^C
garbageServer# sudo ./tsping --print-timestamps --machine-readable=' ' --target-spacing "100000" --sleep-time=0 9.9.9.9 9.9.9.10 208.67.220.220 208.67.220.123 185.228.169.11 208.67.220.2 64.6.64.6 64.6.65.6 2>/dev/null
1678625056.253050 9.9.9.9 0 45856246 45856170 45856170 45856253 7 83 -76
^C
garbageServer# sudo ./tsping --print-timestamps --machine-readable=' ' --target-spacing "100000" --sleep-time=0 9.9.9.9 9.9.9.10 208.67.220.220 208.67.220.123 185.228.169.11 208.67.220.2 64.6.64.6 64.6.65.6 2>/dev/null
1678625057.102732 9.9.9.9 0 45857094 45857020 45857020 45857102 8 82 -74
^C
garbageServer# 
```

**Comment by rany2** [comment] 2023-03-12 12:49
@lynxthecat Could you try updating your tsping? I suspect that https://github.com/Lochnair/tsping/commit/9dd194f388bee3eec231a1c108383cbc9d36ddb6 might be the fix to this issue.

**Comment by moeller0** [comment] 2023-03-12 12:51
`--target-spacing` is in milliseconds, so with ` --target-spacing "100000"` you are asking "100" seconds between individual samples.

Also, please do not use 'spaces (' ')as delimiters that is almost never the right thing and folks should learn to avoid that intuitively.

**Comment by rany2** [comment] 2023-03-12 12:51
> Also, please do not use 'spaces (' ')as delimiters that is almost never the right thing and folks should learn to avoid that intuitively.

I'm simply using the same cmdline arguments as cake-autorate does, I'm not on OpenWRT and can't test cake-autorate directly.

**Comment by moeller0** [comment] 2023-03-12 12:55
> I'm simply using the same cmdline arguments as cake-autorate does,

I doubt that, nobody is requesting 100 seconds between the different reflectors...

Also, when I run your invocation but wait long enough I see more than one response:
```
moeller@work-horse:~/CODE/tsping/builddir$ sudo ./tsping --print-timestamps --machine-readable=' ' --target-spacing "100000" --sleep-time=0 9.9.9.9 9.9.9.10 208.67.220.220 208.67.220.123 185.228.169.11 208.67.220.2 64.6.64.6 64.6.65.6
[sudo] password for moeller: 
Starting tsping 0.2.3 - pinging 8 targets
1678625453.060683 9.9.9.9 0 46253050 46253044 46253044 46253060 10 16 -6
1678625553.060971 9.9.9.10 0 46353050 46353044 46353044 46353060 10 16 -6
^C
```
it is just that 100 seconds is a loooong time to wait in from of a propmt.

**Comment by moeller0** [comment] 2023-03-12 13:00
Let's see what version of tsping @lynxthecat used, but again that is not going to affect the FD race that was observed, the buffering issue IIRC is that we do not see data written to the FIFO immediately but in batches. But that is not the observed phaenotype.

**Comment by moeller0** [comment] 2023-03-12 13:05
> 



> @moeller0 I know this and edited my comment, this was never something I was debating.

Hmmm in my reading you were claiming to be using the exact invocation that autorate uses, which seems unlikely to have been the case. Also generally it helps to describe an issue instead of just dumping some console output...

**Comment by rany2** [comment] 2023-03-12 13:11
> Hmmm in my reading you were claiming to be using the exact invocation that autorate uses, which seems unlikely to have been the case. Also generally it helps to describe an issue instead of just dumping some console output...

Not the exact invocation. As I can't run cake-autorate because my router is on FreeBSD for now, I had to copy https://github.com/lynxthecat/cake-autorate/blob/bc6d02c8058205fe75b6c31786a5bee08036ec46/cake-autorate.sh#L777 and replace ` "${ping_response_interval_ms}"` with a value by myself.

**Comment by moeller0** [comment] 2023-03-12 13:30
Yes, I understand that something like this must have happened. But let's just agree that you figured that out and that specific issue is solved.

**Comment by moeller0** [comment] 2023-03-12 13:41
As a general principle, bash offers an impressive magnitude of specialized constructs that appear ideal for several challenges. However I doubt that the more exotic of these features are all that well tested, especially in combination. So in my toy version I am at keeping things as simple as possible instead of as clever as possible, not only does this work better with my limited capacities, but it is also less likely to get onto bash's "under-tested/de-bugged territory".

**Comment by lynxthecat** [comment] 2023-03-12 14:52
Well this is nuts - this echo:

https://github.com/lynxthecat/cake-autorate/blob/a351aa215632abb53ca1dcaee7322418a28fda44/cake-autorate.sh#L948

gets picked up by:

https://github.com/lynxthecat/cake-autorate/blob/a351aa215632abb53ca1dcaee7322418a28fda44/cake-autorate.sh#L524

**Comment by moeller0** [comment] 2023-03-12 14:58
Humor me and switch back to filenames for the FIFO between tsping and its monitor process and show the same issue, please?

**Comment by moeller0** [comment] 2023-03-12 15:57
> gets picked up by:

Every time or only the first few iterations after starting the monitor process?

**Comment by lynxthecat** [comment] 2023-03-12 16:01
First few iterations @moeller0. If I skip over lines then all is well.

**Comment by moeller0** [comment] 2023-03-12 16:09
Which to me clearly demonstrates that we have issues with file descriptor initialization of children. Here the test is simple, do not use file descriptors where this can happen, but switch back to file names, if the issue is gone I would interpret that as evidence that bash seems to have a race here.
IMHO the solution then would be to dump the file descriptors at least for the FIFO between pinger and its monitor, but instead have the monitor process first create the FIFO and then start the pinger process itself...
Or figure out why what we see is documented behaviour for bash and apply what ever official method is recommended to deal with the issue.
Mind, you I am not pushing this because I hate FDs (I am impartial) but because the old system seems to have worked robustly and reliably, while the replacement apparently does not.

As I indicated above, I consider to be a virtue to use as boring bash-constructs as we can get away with, on the hypothesis that those are the constructs that see wider testing.

**Comment by lynxthecat** [comment] 2023-03-12 16:12
File descriptor initialization seems probable. Going back to regular FIFOs now would mean undoing a lot of the recent changes. I was really hoping there would be a fix here.

**Comment by moeller0** [comment] 2023-03-12 16:16
Well, start with going back the "normal" FIFO for tsping and its monitor to test my hypothesis.

But if that solves the issue, I argue undoing the conversion to FDs is the only realistic option, unless you want to work with bash upstream to have the issue fixed and the fix back-ported to OpenWrt.

I think undoing recent changes is somewhat acceptable if it solves issues/ works around bash bugs, no?

**Comment by lynxthecat** [comment] 2023-03-12 16:20
@patrakov any clue?

**Comment by moeller0** [comment] 2023-03-12 16:26
Even if you disagree about the long term consequences, at least make a quick and dirty test whether going back to filenames for FIFO creation and access solves the issue... it should be easy to simply move  the tsping start into the monitor_tsping() function for this test and comment it out in the earlier call in start_pingers() ...

I would test it in my version, but I did not follow the switch to FDs (because then as now, I lack a convincing justification for the "why") so I do not seem to see the issue in the first place

**Comment by patrakov** [comment] 2023-03-12 18:51
> I am grudgingly beginning to think that.
> 
> @patrakov any clue what's happening here?

I have received the notification, but have no time to actually look at what's happening. Sorry about that! The whole codebase is just too complex for me.

**Comment by lynxthecat** [comment] 2023-03-12 23:36
@moeller0 you are so often on point with your observations. I found out that the file descriptor 1 has indeed somehow got redirected to pinger_fds[pinger] at the point in time of the echo. I verified this by printing out 'ls -l /proc/self/fd/1' for the echo and then also printing out 'ls -l /proc/self/fd/${pinger_fds[pinger]} and they match.

**Comment by rany2** [comment] 2023-03-12 23:47
@lynxthecat No, but I suggest you try to replace this line: https://github.com/lynxthecat/cake-autorate/blob/a351aa215632abb53ca1dcaee7322418a28fda44/cake-autorate.sh#L787

with:

```sh
( proc_man_start "pinger_${pinger}" ${ping_prefix_string} tsping ${ping_extra_args} --print-timestamps --machine-readable=' ' --sleep-time "0" --target-spacing "${ping_response_interval_ms}" "${reflectors[@]:0:${no_pingers}}" 2> /dev/null >&"${pinger_fds[pinger]}" &)
```

**Comment by lynxthecat** [comment] 2023-03-12 23:50
I'll try it. But how would the first call change the shell context? As I understand it just alters fd 1 for the tsping output. I can't work out why it would affect the shell context for the echo.

**Comment by moeller0** [comment] 2023-03-13 06:44
Honestly, this looks insane to me. Unless we have a strong theory that explains the phenotype we saw, we should slow back-off from using file descriptors beyond the point they apparently have been tested and de-bugged (at least on OpenWrt). Doubling down on a broken design is rarely an efficient design or implementation strategy.
And again, I might be wrong and switching to filenames instead of FDs for FIFOs might not actually fix the issue, but that will have diagnostic value as well. The proposed methods looks like "voodoo" lacking a theory what went wrong and how/why this method fixes/works-around that specific brokenness, no?

**Comment by rany2** [comment] 2023-03-13 06:57
@lynxthecat I spawned a subshell and did the redirection inside it so the pinger fds won't be inherited. Based on my understanding of the hours of bash IRC discussions it seems like a possible fix.

@moeller0 agreed, but apparently some seemingly more competent bash programers explained on the bash IRC that this is expected behavior caused by the tsping inheriting the stdout. So I thinking forking and doing the redirection in the subshell would fix it.

**Comment by moeller0** [comment] 2023-03-13 07:05
> @moeller0 agreed, but apparently some seemingly more competent bash programers explained on the bash IRC that this is expected behavior caused by the tsping inheriting the stdout. So I thinking making a subshell and doing the redirection in the subshell would fix it.

Look, "expected" does a lot of work here, especially since that behaviour clearly changes over time. This is a fscking race, and I consider it not to be encouraging that bash programmers consider that race "normal/acceptable/expected".
If switching back to filenames fixes that race for good, that would be my preferred solution. But since I am about to stop caring for 2.0 maybe just ignore me.

**Comment by lynxthecat** [comment] 2023-03-13 07:55
Switching to filenames would fix the issue because the issue has been shown to be related to the paths of the file descriptors having been inadvertently changed. 

As would just skipping over the bad values. 

But I really truly what to figure out what's going on here for my own understanding. It's totally intellectually unsatisfying otherwise. 

@rany2 what I don't understand is why the pinger fd redirection would get inherited. Fd redirection for a single command only applies for that single command doesn't it? Unless exec is called in which case it changes the fd for the figure and such changed fds are inherited. What makes the shell context inherit the single line fd redirection? Isn't this just a red herring? It seems to me it must be something else?

**Comment by rany2** [comment] 2023-03-13 07:56
@lynxthecat could you just switch back to filenames? It's not a difficult change to make and might help with getting this solved once and for all. If it doesn't help then I guess it must be some inheriting issue as the bash people said

**Comment by lynxthecat** [comment] 2023-03-13 10:34
@moeller0 I see the logic in combining pinger creation and destruction with the single monitor process. So monitor process is responsible for starting and stopping the pinger. Is it still a monitor process then? I'm just wondering if that should be renamed? 

I forget the proper way to pipe binary output to while loop. I can check from my previous commits since I did do that ages ago. 

Can either of you remember? @rany2? Is it like:

```
while read do

done< <(ping 2> /dev/null)
```

**Comment by rany2** [comment] 2023-03-13 10:37
@lynxthecat that's it.

**Comment by moeller0** [comment] 2023-03-13 11:02
I would for testing still keep the FIFO, after all changing that aspect totally will not tell us what is happening with the file descriptors...
Later getting rid of that FIFO might or might not be a good idea (since that FIFO is essentially now private to control_and_parse_tsping() [which might be an alternative name to use] its whole lifetime handling can/should be inside control_and_parse_tsping so FIFO or not should be decided by whether it is better than a direct pipe, I have not though deeply about that, what I like a bout a FIFO here is that this would give a way to feed control commands into control_and_parse_tsping to e.g. instruct it to shutdown that are not requiring signals, but that might be my obsession mostly).

> So monitor process is responsible for starting and stopping the pinger. Is it still a monitor process then? I'm just wondering if that should be renamed?

The advantage is that now the pinger PID can simply be maintained as a single variable inside control_and_parse_tsping and there is one thing less to handle for maintain_pingers() to worry about.

We still need a start_pingers loop that deals with multi- and single reflector pingers, but maintain_pingers only needs to interface with the flock of maintain_pingers() processes.

**Comment by lynxthecat** [comment] 2023-03-13 16:42
@rany2 these change the fds:

```
lock()
{
	local path=${1}

	while true; do
		( set -o noclobber; echo "$$" > "${path:?}" ) 2> /dev/null && return 0
		sleep_us 100000
	done
}

unlock()
{
	local path=${1}

	rm -f "${path:?}"
}
```

```
locking l-wx------    1 root     root            64 Mar 13 16:41 /proc/self/fd/1 -> pipe:[2130029]
finished locking l-wx------    1 root     root            64 Mar 13 16:41 /proc/self/fd/1 -> pipe:[2130033]
unlocking l-wx------    1 root     root            64 Mar 13 16:41 /proc/self/fd/1 -> pipe:[2130043]
finished unlocking: l-wx------    1 root     root            64 Mar 13 16:41 /proc/self/fd/1 -> pipe:[2130047]
```

**Comment by lynxthecat** [comment] 2023-03-13 18:11
@rany2 can you see the issue here:

https://pastebin.com/raw/YbuZcXRj

https://pastebin.com/raw/L6hT7t0a

**Comment by lynxthecat** [comment] 2023-03-14 00:43
OK I've figured it out now with help from the bash experts at #bash on Libera. 

The problem is exactly here:

https://github.com/lynxthecat/cake-autorate/blob/a351aa215632abb53ca1dcaee7322418a28fda44/cake-autorate_lib.sh#L128-L145

When this is called with:

https://github.com/lynxthecat/cake-autorate/blob/a351aa215632abb53ca1dcaee7322418a28fda44/cake-autorate.sh#L787

That results in the redirection to pinger_fds[pinger] persisting for many lines within proc_man_start. This provides a wide open window for trap to inherit the redirection 1>pinger_fds[pinger] or any redirection passed to proc_man_start. 

The solution is to have proc_man_start take as an argument any fd for any redirection and then replace:

```
${@} & 
```

with e.g.:

```
${@} > ${fd} &
```

@rany2 any chance you could write a fix for this and pull request?

**Comment by rany2** [comment] 2023-03-14 13:36
@lynxthecat Did you give this a try? https://github.com/lynxthecat/cake-autorate/issues/178#issuecomment-1465333151

**Comment by rany2** [comment] 2023-03-14 14:01
Yep, of course you'll have to drop iputils-ping support but I'd argue that would be a good thing.

**Comment by lynxthecat** [comment] 2023-03-14 14:27
Actually this is what I had in mind: https://github.com/lynxthecat/cake-autorate/commit/b47762d02aaf7646c7e8fdfcca902f9d1aec6613

This incorporates @moeller0's suggestion to integrate the pinger binary execution into the corresponding parsing process. This simplifies the code and renders resolving this file descriptor redirect issue moot.

**Comment by rany2** [comment] 2023-03-14 14:45
Why not close this then?

**Comment by lynxthecat** [comment] 2023-03-14 15:04
Just giving opportunity for any final comments.

**Comment by lynxthecat** [comment] 2023-03-15 18:12
@rany2 so I tested https://github.com/lynxthecat/cake-autorate/issues/178#issuecomment-1465333151 by invoking signal inside the 'start' case of proc_man and indeed this prevents trap execution of change_state_maintain_pingers() from pushing to the pinger_fds[pinger] file descriptor.

**Comment by lynxthecat** [comment] 2023-03-16 18:13
Yes correct but what I mean is pass a third argument before shift 2 to proc_man that is either set to 0 for no redirect or is set to the fd for redirect and then at the "${@} &" set up either no redirect or redirect to the fd passed as an argument. Make sense?

**Comment by rany2** [comment] 2023-03-25 12:40
@lynxthecat whatever works... :shrug:

**Closed** 2023-03-30 20:56 UTC
Labels: bug
