### ISSUE TITLE
kill maintain_pingers() on sleep instead of pausing it?

### ISSUE THREAD

**Issue by moeller0** [lynxthecat/cake-autorate#96] opened 2022-12-30 11:00 UTC
https://github.com/lynxthecat/cake-autorate/blob/c80809586792291e9c5b49791a89804ae415d868/cake-autorate.sh#L1420

Could we not just kill maintain_pingers() for good here? and then start it up for good after sleep? This would probably clean up the reflector maintenance residue we run into?

**Comment by lynxthecat** [comment] 2022-12-30 12:16
On sleep we indeed kill and then start again after sleep. That point in the code forms part of the stall detection whereupon we wait for new pings or new load (or global reflector response timeout) to either resume from stall or go to sleep (on global reflector response timeout). During this stall detection we don't rotate reflectors because the cause it likely connection related and so swapping out reflectors doesn't make sense.

**Comment by moeller0** [comment] 2022-12-30 12:30
Mmmh, so the `	if (( ${PIPESTATUS[0]} == 142 )); then` is the entry point for both sleep and stall-detection?

**Comment by lynxthecat** [comment] 2022-12-30 13:10
That's the entry point for stall-detection since that corresponds to a while loop timeout - so no reflector response. A sleep timeout is rather triggered by a break out of the while loop which hits the 'else' associated with this if statement.

**Comment by lynxthecat** [comment] 2023-01-02 17:35
I think I can close this now. If not. please re-open.

**Closed by lynxthecat** 2023-01-02 17:35 UTC
